package com.example.books.shared.ingest;

import java.io.Serializable;
import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Parsed representation of a PDF document generated by the ingestion pipeline.
 */
public record ParsedPdfDocument(
    String path,
    String checksum,
    long sizeBytes,
    int pageCount,
    Instant sourceEventTime,
    Map<String, String> metadata,
    List<ParsedPdfPage> pages
)
    implements Serializable {}
