package com.example.books.domain;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.books.domain.core.bookpagetext.BookPageText;

public class BookPageTextAsserts {

    public static void assertBookPageTextAllPropertiesEquals(BookPageText expected, BookPageText actual) {
        assertBookPageTextAutoGeneratedPropertiesEquals(expected, actual);
        assertBookPageTextAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertBookPageTextAllUpdatablePropertiesEquals(BookPageText expected, BookPageText actual) {
        assertBookPageTextUpdatableFieldsEquals(expected, actual);
        assertBookPageTextUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertBookPageTextAutoGeneratedPropertiesEquals(BookPageText expected, BookPageText actual) {
        assertThat(actual)
            .as("Verify BookPageText auto generated properties")
            .satisfies(a -> assertThat(a.id()).as("check id").isEqualTo(expected.id()));
    }

    public static void assertBookPageTextUpdatableFieldsEquals(BookPageText expected, BookPageText actual) {
        assertThat(actual)
            .as("Verify BookPageText relevant properties")
            .satisfies(a -> assertThat(a.documentId()).as("check documentId").isEqualTo(expected.documentId()))
            .satisfies(a -> assertThat(a.pageNo()).as("check pageNo").isEqualTo(expected.pageNo()))
            .satisfies(a -> assertThat(a.text()).as("check text").isEqualTo(expected.text()));
    }

    public static void assertBookPageTextUpdatableRelationshipsEquals(BookPageText expected, BookPageText actual) {
        assertThat(actual)
            .as("Verify BookPageText relationships")
            .satisfies(a -> assertThat(a.book()).as("check book").isEqualTo(expected.book()));
    }
}
