package com.example.books.domain;

import static com.example.books.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

import com.example.books.domain.core.bookfile.BookFile;

public class BookFileAsserts {

    public static void assertBookFileAllPropertiesEquals(BookFile expected, BookFile actual) {
        assertBookFileAutoGeneratedPropertiesEquals(expected, actual);
        assertBookFileAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertBookFileAllUpdatablePropertiesEquals(BookFile expected, BookFile actual) {
        assertBookFileUpdatableFieldsEquals(expected, actual);
        assertBookFileUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertBookFileAutoGeneratedPropertiesEquals(BookFile expected, BookFile actual) {
        assertThat(actual)
            .as("Verify BookFile auto generated properties")
            .satisfies(a -> assertThat(a.id()).as("check id").isEqualTo(expected.id()));
    }

    public static void assertBookFileUpdatableFieldsEquals(BookFile expected, BookFile actual) {
        assertThat(actual)
            .as("Verify BookFile relevant properties")
            .satisfies(a -> assertThat(a.pathNorm()).as("check pathNorm").isEqualTo(expected.pathNorm()))
            .satisfies(a -> assertThat(a.sha256()).as("check sha256").isEqualTo(expected.sha256()))
            .satisfies(a -> assertThat(a.sizeBytes()).as("check sizeBytes").isEqualTo(expected.sizeBytes()))
            .satisfies(a -> assertThat(a.mtime()).as("check mtime").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.mtime()))
            .satisfies(a -> assertThat(a.storageUri()).as("check storageUri").isEqualTo(expected.storageUri()))
            .satisfies(a ->
                assertThat(a.firstSeenAt())
                    .as("check firstSeenAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.firstSeenAt())
            )
            .satisfies(a ->
                assertThat(a.lastSeenAt()).as("check lastSeenAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.lastSeenAt())
            );
    }

    public static void assertBookFileUpdatableRelationshipsEquals(BookFile expected, BookFile actual) {
        assertThat(actual)
            .as("Verify BookFile relationships")
            .satisfies(a -> assertThat(a.book()).as("check book").isEqualTo(expected.book()));
    }
}
