package com.example.books.domain;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.books.domain.core.book.Book;

public class BookAsserts {

    public static void assertBookAllPropertiesEquals(Book expected, Book actual) {
        assertBookAutoGeneratedPropertiesEquals(expected, actual);
        assertBookAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertBookAllUpdatablePropertiesEquals(Book expected, Book actual) {
        assertBookUpdatableFieldsEquals(expected, actual);
        assertBookUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertBookAutoGeneratedPropertiesEquals(Book expected, Book actual) {
        assertThat(actual)
            .as("Verify Book auto generated properties")
            .satisfies(a -> assertThat(a.id()).as("check id").isEqualTo(expected.id()));
    }

    public static void assertBookUpdatableFieldsEquals(Book expected, Book actual) {
        assertThat(actual)
            .as("Verify Book relevant properties")
            .satisfies(a -> assertThat(a.documentId()).as("check documentId").isEqualTo(expected.documentId()))
            .satisfies(a -> assertThat(a.title()).as("check title").isEqualTo(expected.title()))
            .satisfies(a -> assertThat(a.author()).as("check author").isEqualTo(expected.author()))
            .satisfies(a -> assertThat(a.lang()).as("check lang").isEqualTo(expected.lang()))
            .satisfies(a -> assertThat(a.pages()).as("check pages").isEqualTo(expected.pages()));
    }

    public static void assertBookUpdatableRelationshipsEquals(Book expected, Book actual) {
        // no relationships on the aggregate root at the moment
    }
}
