package com.example.books.domain;

import static com.example.books.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

import com.example.books.domain.core.ingestevent.IngestEvent;

public class IngestEventAsserts {

    public static void assertIngestEventAllPropertiesEquals(IngestEvent expected, IngestEvent actual) {
        assertIngestEventAutoGeneratedPropertiesEquals(expected, actual);
        assertIngestEventAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertIngestEventAllUpdatablePropertiesEquals(IngestEvent expected, IngestEvent actual) {
        assertIngestEventUpdatableFieldsEquals(expected, actual);
        assertIngestEventUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertIngestEventAutoGeneratedPropertiesEquals(IngestEvent expected, IngestEvent actual) {
        assertThat(actual)
            .as("Verify IngestEvent auto generated properties")
            .satisfies(a -> assertThat(a.id()).as("check id").isEqualTo(expected.id()));
    }

    public static void assertIngestEventUpdatableFieldsEquals(IngestEvent expected, IngestEvent actual) {
        assertThat(actual)
            .as("Verify IngestEvent relevant properties")
            .satisfies(a -> assertThat(a.runId()).as("check runId").isEqualTo(expected.runId()))
            .satisfies(a -> assertThat(a.documentId()).as("check documentId").isEqualTo(expected.documentId()))
            .satisfies(a -> assertThat(a.topic()).as("check topic").isEqualTo(expected.topic()))
            .satisfies(a -> assertThat(a.payload()).as("check payload").isEqualTo(expected.payload()))
            .satisfies(a ->
                assertThat(a.createdAt()).as("check createdAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.createdAt())
            );
    }

    public static void assertIngestEventUpdatableRelationshipsEquals(IngestEvent expected, IngestEvent actual) {
        assertThat(actual)
            .as("Verify IngestEvent relationships")
            .satisfies(a -> assertThat(a.ingestRunId()).as("check ingestRunId").isEqualTo(expected.ingestRunId()));
    }
}
