package com.example.books.domain;

import static com.example.books.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

import com.example.books.domain.core.ingestrun.IngestRun;

public class IngestRunAsserts {

    public static void assertIngestRunAllPropertiesEquals(IngestRun expected, IngestRun actual) {
        assertIngestRunAutoGeneratedPropertiesEquals(expected, actual);
        assertIngestRunAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertIngestRunAllUpdatablePropertiesEquals(IngestRun expected, IngestRun actual) {
        assertIngestRunUpdatableFieldsEquals(expected, actual);
        assertIngestRunUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertIngestRunAutoGeneratedPropertiesEquals(IngestRun expected, IngestRun actual) {
        assertThat(actual)
            .as("Verify IngestRun auto generated properties")
            .satisfies(a -> assertThat(a.id()).as("check id").isEqualTo(expected.id()));
    }

    public static void assertIngestRunUpdatableFieldsEquals(IngestRun expected, IngestRun actual) {
        assertThat(actual)
            .as("Verify IngestRun relevant properties")
            .satisfies(a ->
                assertThat(a.startedAt()).as("check startedAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.startedAt())
            )
            .satisfies(a ->
                assertThat(a.finishedAt()).as("check finishedAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.finishedAt())
            )
            .satisfies(a -> assertThat(a.status()).as("check status").isEqualTo(expected.status()))
            .satisfies(a -> assertThat(a.filesSeen()).as("check filesSeen").isEqualTo(expected.filesSeen()))
            .satisfies(a -> assertThat(a.filesParsed()).as("check filesParsed").isEqualTo(expected.filesParsed()))
            .satisfies(a -> assertThat(a.filesFailed()).as("check filesFailed").isEqualTo(expected.filesFailed()));
    }

    public static void assertIngestRunUpdatableRelationshipsEquals(IngestRun expected, IngestRun actual) {
        // aggregate currently exposes no relationships
    }
}
